version: '3.8'

services:
  api:
    build: .
    container_name: genai-news-api
    ports:
      - "8000:8000"
    volumes:
      - ./downloaded_files:/app/downloaded_files
    env_file:
      - .env
    command: "run_fastapi"
    restart: unless-stopped

  prepare_db:
    build: .
    container_name: genai-news-prepare-db
    volumes:
      - ./downloaded_files:/app/downloaded_files
    env_file:
      - .env
    command: "prepare_db"
    # This service will exit after completion, no need for restart policy 