[tool.ruff]
# Enable linters
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "D",   # pydocstyle
    "N",   # naming conventions
    "UP",  # pyupgrade
    "S",   # flake8-bandit (security)
    "T20", # flake8-print
]

# Ignore specific rules
ignore = [
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
]

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

# Exclude files and directories
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "venv",
    ".venv",
    "downloaded_files",
]

# Line length is 120 chars
line-length = 120

# Target Python version
target-version = "py311"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "D104"]
"tests/**/*.py" = ["D", "S"]

[tool.ruff.pydocstyle]
# Use Google-style docstrings
convention = "google"

[tool.ruff.isort]
known-first-party = ["src"]

[tool.ruff.mccabe]
max-complexity = 10 